baseURL = "https://KhalidCK.github.io"
languageCode = "en-us"
title = "Khalid C. Weblog"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/KhalidCK\">Khalid C.</a> 2018"
disqusShortname = ""
googleAnalytics = ""
# Number of posts per page
Paginate = 5
enableRobotsTXT = true

pygmentsCodeFences=true

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = false# Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
poweredby = false# Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article


[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]

twitter = ""
github = "KhalidCK"
email = "fr.ckhalid@gmail.com"
linkedin = ""
facebook = ""
instagram = ""
codepen = ""

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true
