baseURL = "https://KhalidCK.github.io"
languageCode = "en-us"
title = "Khalid C."
theme = "coder"

[params] # theme parameters
    author = "Khalid Chakhmoun" # author's name
    info = "Think fast & slow" # author's job title or info
    description = "Khalid C's personal website" # site description
    keywords = "blog,machine learning," # site keywords

    # wether you want to hide copyright and credits in the footer
    hideCredits = true
    hideCopyright = true

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/KhalidCK/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"